/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ItemsRequest, itemsRequestSchema } from '../models/itemsRequest';
import { ItemsResponse, itemsResponseSchema } from '../models/itemsResponse';
import { BaseController } from './baseController';

export class ApiController extends BaseController {
  /**
   * @return Response from the API call


   */
  async getAListOfItems(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ItemsResponse>> {
    const req = this.createRequest('GET', '/items');
    return req.callAsJson(itemsResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call


   */
  async createANewItem(
    body: ItemsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/items');
    const mapped = req.prepareArgs({ body: [body, itemsRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.call(requestOptions);
  }
}
