/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Specifications, specificationsSchema } from './specifications';

export interface Details {
  manufacturer?: string;
  warranty?: string;
  specifications?: Specifications;
}

export const detailsSchema: Schema<Details> = object({
  manufacturer: ['manufacturer', optional(string())],
  warranty: ['warranty', optional(string())],
  specifications: [
    'specifications',
    optional(lazy(() => specificationsSchema)),
  ],
});
