/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Item, itemSchema } from './item';

export interface ItemsResponse {
  items?: Item[];
}

export const itemsResponseSchema: Schema<ItemsResponse> = object({
  items: ['items', optional(array(lazy(() => itemSchema)))],
});
