/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ItemPricing, itemPricingSchema } from './containers/itemPricing';
import { Details, detailsSchema } from './details';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface Item {
  id?: bigint;
  name?: string;
  value?: bigint;
  tags?: string[];
  metadata?: Record<string, string>;
  details?: Details;
  status?: StatusEnum;
  pricing?: ItemPricing;
}

export const itemSchema: Schema<Item> = object({
  id: ['id', optional(bigint())],
  name: ['name', optional(string())],
  value: ['value', optional(bigint())],
  tags: ['tags', optional(array(string()))],
  metadata: ['metadata', optional(dict(string()))],
  details: ['details', optional(lazy(() => detailsSchema))],
  status: ['status', optional(statusEnumSchema)],
  pricing: ['pricing', optional(itemPricingSchema)],
});
