/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing3 {
  membershipFee?: number;
  validityPeriod?: string;
}

export const pricing3Schema: Schema<Pricing3> = object({
  membershipFee: ['membershipFee', optional(number())],
  validityPeriod: ['validityPeriod', optional(string())],
});
