/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing5 {
  serviceCharge?: number;
  description?: string;
}

export const pricing5Schema: Schema<Pricing5> = object({
  serviceCharge: ['serviceCharge', optional(number())],
  description: ['description', optional(string())],
});
