/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Pricing2 {
  tax?: number;
  taxRate?: number;
}

export const pricing2Schema: Schema<Pricing2> = object({
  tax: ['tax', optional(number())],
  taxRate: ['taxRate', optional(number())],
});
