/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing {
  price?: number;
  currency?: string;
}

export const pricingSchema: Schema<Pricing> = object({
  price: ['price', optional(number())],
  currency: ['currency', optional(string())],
});
