/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing77 {
  price?: number;
  currency?: string;
  discount?: number;
  validUntil?: string;
  tax?: number;
  taxRate?: number;
  membershipFee?: number;
  validityPeriod?: string;
  shippingCost?: number;
  shippingMethod?: string;
  serviceCharge?: number;
  description?: string;
  installment?: number;
  paymentDue?: string;
}

export const pricing77Schema: Schema<Pricing77> = object({
  price: ['price', optional(number())],
  currency: ['currency', optional(string())],
  discount: ['discount', optional(number())],
  validUntil: ['validUntil', optional(string())],
  tax: ['tax', optional(number())],
  taxRate: ['taxRate', optional(number())],
  membershipFee: ['membershipFee', optional(number())],
  validityPeriod: ['validityPeriod', optional(string())],
  shippingCost: ['shippingCost', optional(number())],
  shippingMethod: ['shippingMethod', optional(string())],
  serviceCharge: ['serviceCharge', optional(number())],
  description: ['description', optional(string())],
  installment: ['installment', optional(number())],
  paymentDue: ['paymentDue', optional(string())],
});
