/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing1 {
  discount?: number;
  validUntil?: string;
}

export const pricing1Schema: Schema<Pricing1> = object({
  discount: ['discount', optional(number())],
  validUntil: ['validUntil', optional(string())],
});
