/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing4 {
  shippingCost?: number;
  shippingMethod?: string;
}

export const pricing4Schema: Schema<Pricing4> = object({
  shippingCost: ['shippingCost', optional(number())],
  shippingMethod: ['shippingMethod', optional(string())],
});
