/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Pricing6 {
  installment?: number;
  paymentDue?: string;
}

export const pricing6Schema: Schema<Pricing6> = object({
  installment: ['installment', optional(number())],
  paymentDue: ['paymentDue', optional(string())],
});
