/**
 * Sample APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Specifications {
  weight?: number;
  dimensions?: string;
  material?: string;
}

export const specificationsSchema: Schema<Specifications> = object({
  weight: ['weight', optional(number())],
  dimensions: ['dimensions', optional(string())],
  material: ['material', optional(string())],
});
